apiVersion: apps/v1
kind: Deployment
metadata:
  name: it-cmds
spec:
  replicas: 1
  selector:
    matchLabels:
      app: it-cmds
  template:
    metadata:
      labels:
        app: it-cmds
    spec:
      containers:
      - name: it-cmds
        image: it-cmd-frontend
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: it-cmds
  labels:
    app: it-cmds
spec:
  type: NodePort
  selector:
    app: it-cmds
  ports:
  - port: 80
    targetPort: 80
